### ISSUE TITLE
Verification required being thrown

### ISSUE THREAD

**Issue by whitecoder** [mwgg/iracing-php#1]
I installed via composer and I keep getting verification required. I can go to the api on iRacing and manually login and have no issues at all. Any ideas on what could be causing this to happen?

[14-Sep-2022 11:44:40 America/Chicago] 
PHP Fatal error:  Uncaught iRacingPHP\Exceptions\AuthenticationFailedException: Verification required. in /home1/public_html/api2/mwgg/iracing-php/src/Api.php:43

Stack trace:
#0 /home1/public_html/api2/mwgg/iracing-php/src/Api.php(176): iRacingPHP\Api->authenticate()
#1 /home1/public_html/api2/mwgg/iracing-php/src/Api.php(142): iRacingPHP\Api->shouldRetryRequest(Object(GuzzleHttp\Psr7\Response), 'Client error: `...', Object(GuzzleHttp\Exception\ClientException))
#2 /home1/public_html/api2/mwgg/iracing-php/src/Data/Stats.php(60): iRacingPHP\Api->request('/stats/member_s...', Array)
#3 /home1/public_html/api2/test.php(6): iRacingPHP\Data\Stats->member_summary()
#4 {main} thrown in /home1/public_html/api2/mwgg/iracing-php/src/Api.php on line 43

test.php contains

include('autoload.php');

use iRacingPHP\iRacing;
$iracing = new iRacing('xxxxxx@xxxxxx.com', 'xxxxxx');
$summary = $iracing->stats->member_summary();

**Comment by mwgg** [comment]
That's odd.

That error message is being returned by the API itself. It appears that the authentication request is sent, credentials are correct, but something else it's not happy about. Unfortunately those API messages aren't really documented, and this one is vague at best.

Can please you try running the sample shell script provided on the [API announcement post](https://forums.iracing.com/discussion/15068/general-availability-of-data-api/p1), the one that's under Authenticating? When you run it, you should see a JSON response, with a long "authcode" if everything goes well, or an error message.

**Comment by mwgg** [comment]
_verificationRequired_ is also one of the fields returned by the authentication request and that script, I'm betting it's 'false' in your case. Makes me wonder if you haven't verified your account email address, or something along those lines. Still only a guess, since I can't find any documentation on what it actually means.

**Comment by whitecoder** [comment]
I tried the sample shell script and I'm getting the same verification required error. I don't think it's an email verification issue as I can login directly to the API [here](https://members-login.iracing.com/?ref=https%3A%2F%2Fmembers-ng.iracing.com%2Fdata%2Fdoc) with no issues at all and can pull up anything within the API itself. I've been an active member since 2008.

Using this code below I can make connection (http code of 200) and write to the cookie jar and get an auth token but I get 401 unauthorized when making a call after that cookie is written using the javascript/jquery method.

`<script>
    var username = "xxxxxx@xxxxxx.com";
    var password = "xxxxxx";

    let hashPassword = CryptoJS.enc.Base64.stringify(
        CryptoJS.SHA256(password + username.toLowerCase())
    );

    $.ajax({
        type: "POST",
        url: "api.php",
        data: {
            email: username,
            password: hashPassword
        },
        success: function(data) {
            console.log(data);
            //do something when request is successful
        },
        dataType: "jsonp"
    });
</script>`

**Comment by mwgg** [comment]
I'd suggest asking about the verification error on the iRacing forums since it doesn't even work with the basic script that they provide. It's something on their end.
Authentication through the browser is handled differently, which is probably why that works.
