### ISSUE TITLE
a Request that Errors still has a Rate Limit

### ISSUE THREAD

**Issue by zane-shus** [mwgg/iracing-php#4]
If i request something that results in a error, example:

`$results = $iracing->results->get(57100175);`

Gives me this:
```
{
    "error": "Not Found",
    "message": "Subsession does not exist."
}
```

And a var_dump on limits, gives this:
```
object(iRacingPHP\Models\RateLimits)#34 (0) {
  ["limit"]=>
  uninitialized(int)
  ["remaining"]=>
  uninitialized(int)
  ["reset"]=>
  uninitialized(int)
}
```

Where in reality API rate limits, are still affected, and as such, the normal: X-RateLimit-LimitX-RateLimit-Remaining, and X-RateLimit-Reset are returned.

![image](https://user-images.githubusercontent.com/50510607/208327567-51e2ef39-2775-4707-9a86-b9c5df23b79a.png)

**Comment by mwgg** [comment]
Fixed with 6f4695b4829b9aa57a18ca4d4c2238e0c6186f4c (v1.4.0).
