### ISSUE TITLE
->member->profile()

### ISSUE THREAD

**Issue by zane-shus** [mwgg/iracing-php#5]
This works:
`$wrapper->member->profile();`
It gets **my** profile.

This however:
`$wrapper->member->profile(12);`
Errors than an **array** must be given.

Even though the API only accepts 1 entry at a time, if I do this:
```
$myarray = array(12);
$wrapper->member->profile($myarray);
```
It still gives me the result for **my** profile, **not** customer 12.

Am I doing something wrong?
This is the api endpoint:
`https://members-ng.iracing.com/data/member/profile?cust_id=12`

thanks

**Comment by mwgg** [comment]
Hi,

All optional parameters should be passed in an associative array, so in your case it will look like this:

```php
$wrapper->member->profile(['cust_id' => 12]);
```

Required parameters are passed separately, like in this example:

```php
$standings = $iracing->league->season_standings(12345, 54321, [
    'car_id' => 123,
    'something_else' => 'stuff'
]);
```

As a side note, `['cust_id' => 12]` is the same thing as `array('cust_id' => 12)`, just a shorter notation in modern PHP versions, so you can use whatever you are used to.

It's a little quirky, but at the time I made this, this is what my brain came up with for passing a mix of required and optional parameters. Perhaps it should have been one or the other, but changing it now would break stuff for people using iracing-php in their projects.

**Comment by zane-shus** [comment]
perfect, thank you for that.
